# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ofd', '0001_initial'), ('ofd', '0002_flight_flightnumber'), ('ofd', '0003_auto_20160629_1603'), ('ofd', '0004_auto_20160629_1603'), ('ofd', '0005_auto_20160629_1619'), ('ofd', '0006_auto_20160629_1628'), ('ofd', '0007_remove_country_name_official'), ('ofd', '0008_airline_country_obj'), ('ofd', '0009_remove_airline_country'), ('ofd', '0010_auto_20160629_1658'), ('ofd', '0011_auto_20160629_1704'), ('ofd', '0012_auto_20160629_1718'), ('ofd', '0013_airport_country'), ('ofd', '0014_remove_airport_country_str'), ('ofd', '0015_auto_20160629_1834'), ('ofd', '0016_auto_20160629_1854'), ('ofd', '0017_remove_aircraft_engine_count'), ('ofd', '0018_auto_20160629_1936'), ('ofd', '0019_auto_20160629_1954'), ('ofd', '0020_flight_flight_duration')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(help_text='The name of the manufacturer.', max_length=64, verbose_name='Manufacturer')),
                ('model', models.CharField(help_text='The model name of the aircraft.', max_length=32, verbose_name='Model Name')),
                ('designator', models.CharField(help_text='Type designator.', max_length=8, verbose_name='Aircraft Code')),
                ('category', models.CharField(choices=[('A', 'Amphibian'), ('G', 'Gyrocopter'), ('H', 'Helicopter'), ('L', 'Landplane'), ('S', 'SeaPlane'), ('T', 'Tilt-wing'), ('U', 'Unknown')], default='U', help_text='Category of aircraft', max_length=1, verbose_name='Category')),
                ('engine_type', models.CharField(choices=[('E', 'Electric'), ('J', 'Jet'), ('T', 'Turboprop'), ('P', 'Piston'), ('U', 'Unknown')], default='U', help_text='Type of engine.', max_length=1, verbose_name='Engine Type')),
                ('engine_count', models.IntegerField(help_text='Number of Engines', verbose_name='Engines')),
            ],
            options={
                'ordering': ['designator'],
                'managed': True,
                'verbose_name_plural': 'Aircraft',
                'verbose_name': 'Aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(help_text='Unique OpenFlights identifier for this airline.', primary_key=True, serialize=False, verbose_name='Airline ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of airline.', max_length=128, verbose_name='Name')),
                ('alias', models.CharField(blank=True, default='', help_text='Alias of the airline.', max_length=128, verbose_name='Name')),
                ('iata', models.CharField(blank=True, default='', help_text='2-letter IATA code, if available.', max_length=2, verbose_name='IATA')),
                ('icao', models.CharField(blank=True, default='', help_text='3-letter IATA code, if available.', max_length=3, verbose_name='ICAO')),
                ('callsign', models.CharField(blank=True, default='', help_text='Airline callsign.', max_length=128, verbose_name='Callsign')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the airline is or has until recently been operational. This field is not reliable.', verbose_name='Is Active')),
            ],
            options={
                'ordering': ['iata'],
                'managed': True,
                'verbose_name_plural': 'Airlines',
                'verbose_name': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(help_text='Unique OpenFlights identifier for this airport.', primary_key=True, serialize=False, verbose_name='Airport ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of airport. May or may not contain the City name.', max_length=128, verbose_name='Name')),
                ('city', models.CharField(blank=True, default='', help_text='Main city served by airport. May be spelled differently from Name.', max_length=128, verbose_name='City')),
                ('iata_faa', models.CharField(blank=True, default='', help_text='3-letter FAA code if located in USA, 3-letter IATA code, for all others. Blank if not assigned.', max_length=3, verbose_name='IATA/FAA')),
                ('icao', models.CharField(blank=True, default='', help_text='4-letter ICAO code. Blank if not assigned.', max_length=4, verbose_name='ICAO')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, usually to six significant digits. Negative is South, positive is North.', max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, usually to six significant digits. Negative is West, positive is East.', max_digits=11, verbose_name='Longitude')),
                ('altitude', models.IntegerField(help_text='In feet.', verbose_name='Altitude')),
                ('timezone', models.DecimalField(decimal_places=2, help_text='Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5.', max_digits=4, verbose_name='Time Zone')),
                ('dst', models.CharField(choices=[('E', 'Europe'), ('A', 'US/Canada'), ('S', 'South America'), ('O', 'Australia'), ('Z', 'New Zealand'), ('N', 'None'), ('U', 'Unknown')], default='U', help_text='Daylight savings time.', max_length=2, verbose_name='DST')),
                ('tz_db', models.CharField(blank=True, default='', help_text="Timezone in 'tz' (Olson) format, eg., 'America/Los_Angeles'.", max_length=128, verbose_name='TZ Database Time Zone')),
            ],
            options={
                'ordering': ['iata_faa'],
                'managed': True,
                'verbose_name_plural': 'Airports',
                'verbose_name': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_code', models.CharField(blank=True, default='', max_length=2, verbose_name='Country ISO Code (2-letter)')),
                ('name', models.CharField(blank=True, default='', help_text='Country or territory', max_length=128, verbose_name='Country Name')),
            ],
            options={
                'ordering': ['iso_code'],
                'managed': True,
                'verbose_name_plural': 'Countries',
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_codeshare', models.BooleanField(default=False, help_text='Is this flight is a codeshare (that is, not operated by Airline, but another carrier).', verbose_name='Is Codeshare')),
                ('stops', models.IntegerField(default=0, help_text='Number of stops on this flight. 0=nonstop.', verbose_name='Stops')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline')),
                ('airport_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_from_rel', to='ofd.Airport')),
                ('airport_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_to_rel', to='ofd.Airport')),
                ('equipment', models.ManyToManyField(to='ofd.Aircraft')),
            ],
            options={
                'ordering': ['airline', 'airport_from', 'airport_to'],
                'managed': True,
                'verbose_name_plural': 'Routes',
                'verbose_name': 'Route',
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Country'),
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Country'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('dow_1Su', models.BooleanField(default=True, verbose_name='1 Sundays')),
                ('dow_2Mo', models.BooleanField(default=True, verbose_name='2 Mondays')),
                ('dow_3Tu', models.BooleanField(default=True, verbose_name='3 Tuesdays')),
                ('dow_4We', models.BooleanField(default=True, verbose_name='4 Wednesdays')),
                ('dow_5Th', models.BooleanField(default=True, verbose_name='5 Thursdays')),
                ('dow_6Fr', models.BooleanField(default=True, verbose_name='6 Fridays')),
                ('dow_7Sa', models.BooleanField(default=True, verbose_name='7 Saturdays')),
                ('departs_local', models.TimeField(blank=True)),
                ('arrives_local', models.TimeField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Aircraft')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Route')),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'verbose_name': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='FlightNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Flight')),
            ],
            options={
                'verbose_name_plural': 'Flight Numbers',
                'verbose_name': 'Flight Number',
            },
        ),
        migrations.RemoveField(
            model_name='airline',
            name='country',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'ordering': ['iso_code2', 'name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code2',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='ISO 2'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code3',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='ISO 3'),
        ),
        migrations.AddField(
            model_name='country',
            name='un_m49',
            field=models.IntegerField(blank=True, null=True, verbose_name='UN M.49 Numeric Code'),
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofd.Country', verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Name')),
                ('airlines', models.ManyToManyField(to='ofd.Airline')),
            ],
            options={
                'verbose_name_plural': 'Alliances',
                'verbose_name': 'Alliance',
            },
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'managed': True, 'ordering': ['iata'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='iata_faa',
            new_name='iata',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofd.Country'),
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='engine_count',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturer',
            field=models.CharField(blank=True, default='', help_text='The name of the manufacturer.', max_length=64, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.CharField(blank=True, default='', help_text='The model name of the aircraft.', max_length=32, verbose_name='Model Name'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='route',
            name='airport_from',
        ),
        migrations.RemoveField(
            model_name='route',
            name='airport_to',
        ),
        migrations.RemoveField(
            model_name='route',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.AddField(
            model_name='flight',
            name='airport_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_from_rel', to='ofd.Airport', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airport_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_to_rel', to='ofd.Airport', verbose_name='To'),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='flight',
            name='operator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='flight',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofd.Aircraft', verbose_name='Aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrives_day_offset',
            field=models.IntegerField(default=0, help_text='This is the number of dates earlier or later you arrive. For instance, if the flight lands at 2:00am, then this should be 1, because it is the next day.', verbose_name='Day Offset'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrives_local',
            field=models.TimeField(blank=True, verbose_name='Arrives'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departs_local',
            field=models.TimeField(blank=True, verbose_name='Departs'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_1Su',
            field=models.BooleanField(default=True, verbose_name='Sun'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_2Mo',
            field=models.BooleanField(default=True, verbose_name='Mon'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_3Tu',
            field=models.BooleanField(default=True, verbose_name='Tue'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_4We',
            field=models.BooleanField(default=True, verbose_name='Wed'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_5Th',
            field=models.BooleanField(default=True, verbose_name='Thu'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_6Fr',
            field=models.BooleanField(default=True, verbose_name='Fri'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dow_7Sa',
            field=models.BooleanField(default=True, verbose_name='Sat'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='operator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline', verbose_name='Operated By'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
