# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(help_text='The name of the manufacturer.', max_length=64, verbose_name='Manufacturer')),
                ('model', models.CharField(help_text='The model name of the aircraft.', max_length=32, verbose_name='Model Name')),
                ('designator', models.CharField(help_text='Type designator.', max_length=8, verbose_name='Aircraft Code')),
                ('category', models.CharField(choices=[('A', 'Amphibian'), ('G', 'Gyrocopter'), ('H', 'Helicopter'), ('L', 'Landplane'), ('S', 'SeaPlane'), ('T', 'Tilt-wing'), ('U', 'Unknown')], default='U', help_text='Category of aircraft', max_length=1, verbose_name='Category')),
                ('engine_type', models.CharField(choices=[('E', 'Electric'), ('J', 'Jet'), ('T', 'Turboprop'), ('P', 'Piston'), ('U', 'Unknown')], default='U', help_text='Type of engine.', max_length=1, verbose_name='Engine Type')),
                ('engine_count', models.IntegerField(help_text='Number of Engines', verbose_name='Engines')),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['designator'],
                'verbose_name': 'Aircraft',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(help_text='Unique OpenFlights identifier for this airline.', primary_key=True, serialize=False, verbose_name='Airline ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of airline.', max_length=128, verbose_name='Name')),
                ('alias', models.CharField(blank=True, default='', help_text='Alias of the airline.', max_length=128, verbose_name='Name')),
                ('iata', models.CharField(blank=True, default='', help_text='2-letter IATA code, if available.', max_length=2, verbose_name='IATA')),
                ('icao', models.CharField(blank=True, default='', help_text='3-letter IATA code, if available.', max_length=3, verbose_name='ICAO')),
                ('callsign', models.CharField(blank=True, default='', help_text='Airline callsign.', max_length=128, verbose_name='Callsign')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the airline is or has until recently been operational. This field is not reliable.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name_plural': 'Airlines',
                'ordering': ['iata'],
                'verbose_name': 'Airline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(help_text='Unique OpenFlights identifier for this airport.', primary_key=True, serialize=False, verbose_name='Airport ID')),
                ('name', models.CharField(blank=True, default='', help_text='Name of airport. May or may not contain the City name.', max_length=128, verbose_name='Name')),
                ('city', models.CharField(blank=True, default='', help_text='Main city served by airport. May be spelled differently from Name.', max_length=128, verbose_name='City')),
                ('iata_faa', models.CharField(blank=True, default='', help_text='3-letter FAA code if located in USA, 3-letter IATA code, for all others. Blank if not assigned.', max_length=3, verbose_name='IATA/FAA')),
                ('icao', models.CharField(blank=True, default='', help_text='4-letter ICAO code. Blank if not assigned.', max_length=4, verbose_name='ICAO')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, usually to six significant digits. Negative is South, positive is North.', max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, usually to six significant digits. Negative is West, positive is East.', max_digits=11, verbose_name='Longitude')),
                ('altitude', models.IntegerField(help_text='In feet.', verbose_name='Altitude')),
                ('timezone', models.DecimalField(decimal_places=2, help_text='Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5.', max_digits=4, verbose_name='Time Zone')),
                ('dst', models.CharField(choices=[('E', 'Europe'), ('A', 'US/Canada'), ('S', 'South America'), ('O', 'Australia'), ('Z', 'New Zealand'), ('N', 'None'), ('U', 'Unknown')], default='U', help_text='Daylight savings time.', max_length=2, verbose_name='DST')),
                ('tz_db', models.CharField(blank=True, default='', help_text="Timezone in 'tz' (Olson) format, eg., 'America/Los_Angeles'.", max_length=128, verbose_name='TZ Database Time Zone')),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'ordering': ['iata_faa'],
                'verbose_name': 'Airport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=2, verbose_name='Country ISO Code (2-letter)')),
                ('name', models.CharField(blank=True, default='', help_text='Country or territory', max_length=128, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['iso_code'],
                'verbose_name': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_codeshare', models.BooleanField(default=False, help_text='Is this flight is a codeshare (that is, not operated by Airline, but another carrier).', verbose_name='Is Codeshare')),
                ('stops', models.IntegerField(default=0, help_text='Number of stops on this flight. 0=nonstop.', verbose_name='Stops')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Airline')),
                ('airport_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_from_rel', to='ofd.Airport')),
                ('airport_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_to_rel', to='ofd.Airport')),
                ('equipment', models.ManyToManyField(to='ofd.Aircraft')),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'ordering': ['airline', 'airport_from', 'airport_to'],
                'verbose_name': 'Route',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Country'),
        ),
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofd.Country'),
        ),
    ]
